### ISSUE TITLE
Getting Crashed on Android OS Version below 5.0

### ISSUE THREAD

**Issue by SaichhaKale** [castorflex/VerticalViewPager#25]
08-04 18:31:16.700 26491-26491/com.app.bollywoodtimes E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.app.bollywoodtimes, PID: 26491
                                                                        java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.bollywoodtimes/com.app.bollywoodtimes.Activity.BollywoodTimesApp}: android.view.InflateException: Binary XML file line #18: Error inflating class fr.castorflex.android.verticalviewpager.VerticalViewPager
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2187)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: android.view.InflateException: Binary XML file line #18: Error inflating class fr.castorflex.android.verticalviewpager.VerticalViewPager
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:707)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                            at com.app.bollywoodtimes.Fragment.HomeScreen.onCreateView(HomeScreen.java:61)
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339)
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602)
                                                                            at com.app.bollywoodtimes.Activity.SocialLoginActivity.onStart(SocialLoginActivity.java:436)
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
                                                                            at android.app.Activity.performStart(Activity.java:5247)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                                            at dalvik.system.NativeStart.main(Native Method) 
                                                                         Caused by: java.lang.ClassNotFoundException: Didn't find class "fr.castorflex.android.verticalviewpager.VerticalViewPager" on path: DexPathList[[zip file "/data/app/com.app.bollywoodtimes-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.app.bollywoodtimes-2, /vendor/lib, /system/lib]]
                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                            at android.view.LayoutInflater.createView(LayoutInflater.java:559)
                                                                            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                            at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                            at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                            at com.app.bollywoodtimes.Fragment.HomeScreen.onCreateView(HomeScreen.java:61) 
                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974) 
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067) 
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252) 
                                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738) 
                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617) 
                                                                            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:339) 
                                                                            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:602) 
                                                                            at com.app.bollywoodtimes.Activity.SocialLoginActivity.onStart(SocialLoginActivity.java:436) 
                                                                            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171) 
                                                                            at android.app.Activity.performStart(Activity.java:5247) 
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2160) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2236) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:138) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1199) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                            at android.os.Looper.loop(Looper.java:136) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5095) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by Siddharthflo** [comment]
@SaichhaKale I have also encountered the same issue. In mine, it is crashing on O.S 6 also. Did you find any solution to it?
